version: "3"
services:
  mysql:
    image: mariadb:10.4.12
    command: --character-set-server=utf8mb4
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e5sub
    restart: always
    container_name: mysql
  e5bot:
    image: iyear/e5subbot
    volumes:
      - ./e5bot/config.yml:/root/config.yml
      - ./e5bot/log:/root/log
    restart: always
    container_name: e5bot
