name: Docker Build
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag
        id: tag
        run: echo ::set-output name=VER::${GITHUB_REF/refs\/tags\//}
      - name: Get core
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
          push: true
          tags: |
            iyear/e5subbot:latest
            iyear/e5subbot:${{ steps.tag.outputs.VER }}